// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACwE7FQT2pt1COFCB4zEKEja3ZDrzT9cE',
    appId: '1:90577712249:web:e4f034632ba642bfddd0a8',
    messagingSenderId: '90577712249',
    projectId: 'syncteam-staging',
    authDomain: 'syncteam-staging.firebaseapp.com',
    databaseURL: 'https://syncteam-staging-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'syncteam-staging.firebasestorage.app',
    measurementId: 'G-P1FT1S9Z4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzFERfW7ih6-KU31OEuYy8tVEWgPbUWOs',
    appId: '1:90577712249:android:97858d0a1e5d8012ddd0a8',
    messagingSenderId: '90577712249',
    projectId: 'syncteam-staging',
    databaseURL: 'https://syncteam-staging-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'syncteam-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Jw0jETrgO7Qg9yryJjMyhmqnFvcLOgo',
    appId: '1:90577712249:ios:2585c7fa21b75d0cddd0a8',
    messagingSenderId: '90577712249',
    projectId: 'syncteam-staging',
    databaseURL: 'https://syncteam-staging-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'syncteam-staging.firebasestorage.app',
    iosClientId: '90577712249-m9145fqto57g4plpl1k9r7froih15sbk.apps.googleusercontent.com',
    iosBundleId: 'com.gayathriehapukotuwa.syncteamapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Jw0jETrgO7Qg9yryJjMyhmqnFvcLOgo',
    appId: '1:90577712249:ios:2585c7fa21b75d0cddd0a8',
    messagingSenderId: '90577712249',
    projectId: 'syncteam-staging',
    databaseURL: 'https://syncteam-staging-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'syncteam-staging.firebasestorage.app',
    iosClientId: '90577712249-m9145fqto57g4plpl1k9r7froih15sbk.apps.googleusercontent.com',
    iosBundleId: 'com.gayathriehapukotuwa.syncteamapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACwE7FQT2pt1COFCB4zEKEja3ZDrzT9cE',
    appId: '1:90577712249:web:fdf431aa129965c7ddd0a8',
    messagingSenderId: '90577712249',
    projectId: 'syncteam-staging',
    authDomain: 'syncteam-staging.firebaseapp.com',
    databaseURL: 'https://syncteam-staging-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'syncteam-staging.firebasestorage.app',
    measurementId: 'G-CHSFEXPG44',
  );
}
